# Generated by Django 3.1.7 on 2021-02-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
